version: "3"
services:
  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 'rootroot'
      MYSQL_DATABASE: 'patientdata'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'rootroot'
      ports:
        3306:3306
      expose:
        "3306"



