version: '3'

services:
  patient-jdbc:
    build:
      context: .
      dockerfile: Dockerfile
  #  image: patient-jdbc
    container_name: patient-jdbc
    ports:
      - '8081:8081'
    #restart: always
    depends_on:
      - db
  #  networks:
  #    - default

  # Database Service (Mysql)
  db:
    image: mysql:latest
    container_name: db
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'patientdata'
      MYSQL_ROOT_PASSWORD: 'rootroot'
     # MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'rootroot'

  #  networks:
  #    - default
#networks:
  #default:


