version: '3'
services:
  # Database Service (Mysql)
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - '3307:3306'
    #command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: patientdata
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_PASSWORD: rootroot

  patient-information:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    #  image: patient
    ports:
      - "8081:8081"
    restart: always
    environment:
       PATIENTINFORMATION_DB_HOST: db:3307
       PATIENTINFORMATION_DB_USER: root
       PATIENTINFORMATION_DB_PASSWORD: rootroot
       PATIENTINFORMATION_DB_NAME: patientdata
volumes:
     db_data: {}

