version: "3"
services:
  db:
    image: mongo:3.2.4
    container_name: "db"
    ports:
      - 27017:27017
    command: --smallfiles
  notes:
    image: notes
    ports:
      - 8080:8080
    links:
      - db
}